#ifndef TEST_CROWELLCHATQTCLIENT_UI_PAGES_HELLO_WORLD_H
#define TEST_CROWELLCHATQTCLIENT_UI_PAGES_HELLO_WORLD_H

#include <QQmlExtensionPlugin>
#include <QtQuickTest>

#endif //TEST_CROWELLCHATQTCLIENT_UI_PAGES_HELLO_WORLD_H
